[tool.black]
line-length = 120
target-version = ["py311"]
include = '\.py$'
exclude = '''
/(
    venv
  | .venv
  | __pycache__
  | .git
)/
'''

[tool.isort]
profile = "black"
line_length = 121
skip = ["venv", ".venv"]