name: CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    types: [closed]
    branches: ["master"]

jobs:
  # linter job
  lint:
    name: Lint (black, isort, flake8)
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - name: Run Black (check)
        run: black --check .

      - name: Run isort (check)
        run: isort --profile black --check-only .

      - name: Run flake8
        run: flake8 --exclude=venv,env,migrations


  # test job
  tests:
    name: Tests + Coverage
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: pytest --cov=src --cov-report=xml --cov-fail-under=30

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml


  # deploy job
  deploy:
    name: Deploy to Render
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Trigger Render Deploy Hook
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl -X POST "$RENDER_DEPLOY_HOOK"


   # health check job
  healthcheck:
    name: Health Check on Render
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Wait for Render healthcheck
        env:
          HEALTHCHECK_URL: ${{ secrets.RENDER_HELTHCHECK_URL }}
        run: |
          echo "Waiting for production health check at: $RENDER_HELTHCHECK_URL"
          
          if [ -z "$HEALTHCHECK_URL" ]; then
            echo "ERROR: RENDER_HELTHCHECK_URL empty! Check plz GitHub Secrets."
            exit 1
          fi
          
          for i in {1..40}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" -L --connect-timeout 5 "$RENDER_HELTHCHECK_URL" || echo "000")

            echo "Attempt $i/40: Received status $STATUS"

            if [ "$STATUS" = "200" ]; then
              echo "Service is healthy!"
              exit 0
            fi

            sleep 10
          done

          echo "Service did not pass healthcheck (Last status: $STATUS)!"
          exit 1
